export { default as Tile1 } from './tile-1'
export { default as Tile2 } from './tile-2'
export { default as Tile3 } from './tile-3'
export { default as Tile4 } from './tile-4'
export { default as Tile5 } from './tile-5'
export { default as Logo } from './logo'
export { default as PriceGradient } from './price-gradient'
